// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Otp struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Model     string    `json:"model"`
	ModelID   string    `json:"model_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID              int64          `json:"id"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Email           string         `json:"email"`
	Password        string         `json:"password"`
	Phone           sql.NullString `json:"phone"`
	Country         sql.NullString `json:"country"`
	City            sql.NullString `json:"city"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	IsEmailVerified bool           `json:"is_email_verified"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	Deleted         bool           `json:"deleted"`
}
