// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateOtp(ctx context.Context, arg CreateOtpParams) (Otp, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredOtps(ctx context.Context) error
	DeleteOtpByID(ctx context.Context, id int64) error
	GetOtp(ctx context.Context, arg GetOtpParams) (Otp, error)
	GetOtpByCodeAndModel(ctx context.Context, arg GetOtpByCodeAndModelParams) (Otp, error)
	GetOtpByID(ctx context.Context, id int64) (Otp, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
